executables:
  titaniumkiwi:
    source-dirs: src
    main: Main.hs
    ghc-options: -threaded
extra-source-files: []
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
  - base
  - optparse-applicative
  - optparse-text
  # common
  - aeson
  - bytestring
  - stm
  - split
  - text
  - time
  - thyme
  - binary
  - binary-orphans
  - old-locale
  - directory
  - pretty-simple
  - string-conversions
  - network
  - unordered-containers
  - containers
  - rainbox
  - rainbow
  - unix
  - brick
  - vty
  - microlens
  - microlens-th
  - typed-process
  - vector
name: TitaniumKiwi
version: '0.1.0.0'
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
